name: PR Canary Release
env:
  CI: true
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  PR_NUMBER: ${{ github.event.number }}
  BUILD_NUMBER: ${{ github.run_number }}
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
    branches:
      - main
jobs:
  pr-canary-release:
    if: ${{ contains(github.event.pull_request.title, '[canary]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.16'
      - name: Build
        run: npm run setup
      - name: Publish Canary Release
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
          npx lerna publish --canary --exact --preid=canary-$PR_NUMBER-$BUILD_NUMBER --dist-tag=canary-$PR_NUMBER --include-merged-tags --yes
